name: Build and publish wheels

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]
  release:
    types:
      - published
jobs:
  build-matrix:
    strategy:
      fail-fast: False
      matrix:
        os: [ubuntu, windows]
        python-version: [3.11, 3.12]

    name: ${{ matrix.os }} with Python ${{ matrix.python-version }} built and tests
    runs-on: ${{ matrix.os }}-latest
    timeout-minutes: 20

    steps:
      # Setup the directories
      - name: Setup directories
        run: |
          mkdir pycanha-project
          cd pycanha-project
          mkdir pycanha-core pycanha-core-python
        shell: bash

      - name: Check out pycanha-core-python repo
        uses: actions/checkout@v3
        with:
          path: pycanha-project/pycanha-core-python

      - name: Check out pycanha-core repo
        uses: actions/checkout@v3
        with:
          repository: pycanha-project/pycanha-core
          path: pycanha-project/pycanha-core

      - name: Setup python
        uses: actions/setup-python@v4
        with:
          python-version: ${{ matrix.python-version }}

      # Build/install pycanha-core-python bindings with test dependencies
      - name: Build pycanha-core-python
        run: |
          cd pycanha-project/pycanha-core-python
          pip install .[test,build]
        shell: bash

      # Run tests
      - name: Run tests
        run: |
          cd pycanha-project/pycanha-core-python
          pytest
        shell: bash

      # Build wheels
      - name: Build sddist and wheels
        run: |
          cd pycanha-project/pycanha-core-python
          python -m build

      - uses: actions/upload-artifact@v4
        with:
          name: 'pycanha-dist-files'
          path: pycanha-project/pycanha-core-python/dist/*
          overwrite: true # To overwrite the sdist

  upload_pypi:
    name: Publish to PyPI
    needs: [build-matrix]
    runs-on: ubuntu-latest
    environment: testpypi
    permissions:
      id-token: write
    if: github.event_name == 'release' && github.event.action == 'published'
    # or, alternatively, upload to PyPI on every tag starting with 'v' (remove on: release above to use this)
    # if: github.event_name == 'push' && startsWith(github.ref, 'refs/tags/v')
    steps:
      - uses: actions/download-artifact@v4
        with:
          # unpacks all CIBW artifacts into dist/
          pattern: pycanha-dist-files*
          path: dist
          merge-multiple: true

      - uses: pypa/gh-action-pypi-publish@release/v1
        with:
          repository-url: https://test.pypi.org/legacy/

